/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-08 07:12:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class createAuction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Create an Auction</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<a href='success.jsp'>[Return to Home Page]</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("<h1>Create an Auction</h1>\n");
      out.write("\n");
      out.write("<form id=\"createAuctionForm\" action=\"insertAuction.jsp\" method=\"POST\">\n");
      out.write("\n");
      out.write("\n");
      out.write("	Item title: \n");
      out.write("	<input type =\"text\" name=\"item_title\"><br><br>\n");
      out.write("	\n");
      out.write("	Description:\n");
      out.write("	<input type =\"text\" name=\"item_description\"><br><br>\n");
      out.write("	\n");
      out.write("	Category:<br> \n");
      out.write("	<label><input type=\"radio\" name=\"category\" value=\"shirt\" checked>Shirt</label><br>\n");
      out.write("	<label><input type=\"radio\" name=\"category\" value=\"pants\">Pants</label><br>\n");
      out.write("	<label><input type=\"radio\" name=\"category\" value=\"hoodie\">Hoodie</label><br><br> \n");
      out.write("	\n");
      out.write("	Brand: <input type =\"text\" name=\"brand\"><br><br> \n");
      out.write("	Color: <input type =\"text\" name=\"color\"><br><br> \n");
      out.write("	\n");
      out.write("	Size: <br> \n");
      out.write("	<label><input type=\"radio\" name=\"size\" value=\"XS\" checked>XS</label><br>\n");
      out.write("	<label><input type=\"radio\" name=\"size\" value=\"S\">S</label><br>\n");
      out.write("	<label><input type=\"radio\" name=\"size\" value=\"M\">M</label><br> \n");
      out.write("	<label><input type=\"radio\" name=\"size\" value=\"L\">L</label><br>\n");
      out.write("	<label><input type=\"radio\" name=\"size\" value=\"XL\">XL</label><br><br> \n");
      out.write("	\n");
      out.write("	Condition:<br> \n");
      out.write("	<label><input type=\"radio\" name=\"clothing_condition\" value=\"new\" checked>New</label><br>\n");
      out.write("	<label><input type=\"radio\" name=\"clothing_condition\" value=\"used\">Used</label><br>\n");
      out.write("	<label><input type=\"radio\" name=\"clothing_condition\" value=\"fair\">Fair</label><br><br> \n");
      out.write("	\n");
      out.write("	Starting price: <input type=\"number\" name=\"start_price\"><br><br> \n");
      out.write("	Bid Increment: <input type=\"number\" name=\"bid_increment\"><br><br> \n");
      out.write("	Hidden Minimum Price: <input type=\"number\" name=\"hidden_min_price\"><br><br> \n");
      out.write("	\n");
      out.write("	Closing Date: <input type=\"date\" name=\"closing_date\">\n");
      out.write("	Closing time: <input type=\"time\" name=\"closing_time\"><br><br>\n");
      out.write("	\n");
      out.write("	<button type=\"submit\">Create Auction</button>\n");
      out.write("	\n");
      out.write("	<p id=\"errorMessage\" style = \"color:red;\"></p>\n");
      out.write("	\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	\n");
      out.write("document.getElementById(\"createAuctionForm\").addEventListener(\"submit\", function(event){\n");
      out.write("		\n");
      out.write("	const form = event.target;\n");
      out.write("	const error = document.getElementById(\"errorMessage\");\n");
      out.write("	error.textContent = \"\";\n");
      out.write("	\n");
      out.write("	const item_title = form.elements[\"item_title\"].value.trim();\n");
      out.write("	const item_description = form.elements[\"item_description\"].value.trim();\n");
      out.write("	const category = form.elements[\"category\"].value;\n");
      out.write("	const brand = form.elements[\"brand\"].value.trim();\n");
      out.write("	const color = form.elements[\"color\"].value.trim();\n");
      out.write("	const size = form.elements[\"size\"].value;\n");
      out.write("	const clothing_condition = form.elements[\"clothing_condition\"].value;\n");
      out.write("	const start_price = form.elements[\"start_price\"].value.trim();\n");
      out.write("	const bid_increment = form.elements[\"bid_increment\"].value.trim();\n");
      out.write("	const hidden_min_price = form.elements[\"hidden_min_price\"].value.trim();\n");
      out.write("	const closing_date = form.elements[\"closing_date\"].value.trim();\n");
      out.write("	const closing_time = form.elements[\"closing_time\"].value.trim();\n");
      out.write("		\n");
      out.write("	if (item_title === \"\" || item_description === \"\" || category === \"\" || brand === \"\" || \n");
      out.write("			color === \"\" || size === \"\" || clothing_condition === \"\" || start_price === \"\" || \n");
      out.write("				bid_increment === \"\" || hidden_min_price === \"\" || closing_date === \"\" || \n");
      out.write("					closing_time === \"\") {\n");
      out.write("		error.textContent = \"Error: Please fill in all required fields.\";\n");
      out.write("		event.preventDefault();\n");
      out.write("	}\n");
      out.write("		\n");
      out.write("});\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
