/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-08 07:26:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import com.cs336.pkg.ApplicationDB;

public final class insertBid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.cs336.pkg.ApplicationDB");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Process Bid</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");

String auctionIdStr = request.getParameter("auction_id");
String bidAmountStr = request.getParameter("bid_amount");
String currentUser = "" + session.getAttribute("user");

try {
	int auctionId = Integer.parseInt(auctionIdStr);
	int bidAmount = Integer.parseInt(bidAmountStr);
	
	ApplicationDB db = new ApplicationDB();
	Connection con = db.getConnection();
	
	con.setAutoCommit(false);
	
	String checkAuction = "SELECT start_price, bid_increment, seller, " +
			"(SELECT MAX(amount) FROM bids WHERE auction_id = ?) as current_bid " +
			"FROM auction WHERE auction_id = ? AND auction_status = 'active';";
	PreparedStatement ps1 = con.prepareStatement(checkAuction);
	ps1.setInt(1, auctionId);
	ps1.setInt(2, auctionId);
	ResultSet rs = ps1.executeQuery();
	
	if (rs.next()) {
		int startPrice = rs.getInt("start_price");
		int bidIncrement = rs.getInt("bid_increment");
		String seller = rs.getString("seller");
		Integer currentBid = (Integer) rs.getObject("current_bid");
		int minBid = (currentBid != null) ? currentBid + bidIncrement : startPrice;
		
		if (seller.equals(currentUser)) {
			out.println("<p style='color:red;'>Error: You cannot bid on your own auction.</p>");
			con.rollback();
		} else if (bidAmount < minBid) {
			out.println("<p style='color:red;'>Error: Bid amount must be at least $" + minBid + "</p>");
			con.rollback();
		} else {
			String insertBid = "INSERT INTO bids (auction_id, username, amount, bid_time) VALUES (?, ?, ?, NOW());";
			PreparedStatement ps2 = con.prepareStatement(insertBid);
			ps2.setInt(1, auctionId);
			ps2.setString(2, currentUser);
			ps2.setInt(3, bidAmount);
			ps2.executeUpdate();
			
			String getPreviousBidders = "SELECT DISTINCT username FROM bids WHERE auction_id = ? AND username != ?;";
			PreparedStatement ps3 = con.prepareStatement(getPreviousBidders);
			ps3.setInt(1, auctionId);
			ps3.setString(2, currentUser);
			ResultSet bidders = ps3.executeQuery();
			
			String insertAlert = "INSERT INTO alerts (username, message) VALUES (?, ?);";
			PreparedStatement ps4 = con.prepareStatement(insertAlert);
			
			while (bidders.next()) {
				String bidderUsername = bidders.getString("username");
				String message = "A higher bid of $" + bidAmount + " has been placed on auction #" + auctionId;
				ps4.setString(1, bidderUsername);
				ps4.setString(2, message);
				ps4.executeUpdate();
			}
			
			String checkAutoBids = "SELECT username, upper_limit, bid_increment FROM auto_bids " +
					"WHERE auction_id = ? AND username != ? AND upper_limit > ?;";
			PreparedStatement ps5 = con.prepareStatement(checkAutoBids);
			ps5.setInt(1, auctionId);
			ps5.setString(2, currentUser);
			ps5.setInt(3, bidAmount);
			ResultSet autoBids = ps5.executeQuery();
			
			int highestAutoBid = bidAmount;
			String highestAutoBidder = null;
			
			while (autoBids.next()) {
				String autoBidder = autoBids.getString("username");
				int upperLimit = autoBids.getInt("upper_limit");
				int autoIncrement = autoBids.getInt("bid_increment");
				
				int newAutoBid = Math.min(highestAutoBid + autoIncrement, upperLimit);
				
				if (newAutoBid > highestAutoBid) {
					highestAutoBid = newAutoBid;
					highestAutoBidder = autoBidder;
				}
			}
			
			if (highestAutoBidder != null) {
				String insertAutoBid = "INSERT INTO bids (auction_id, username, amount, bid_time) VALUES (?, ?, ?, NOW());";
				PreparedStatement ps6 = con.prepareStatement(insertAutoBid);
				ps6.setInt(1, auctionId);
				ps6.setString(2, highestAutoBidder);
				ps6.setInt(3, highestAutoBid);
				ps6.executeUpdate();
				
				String notifyOutbid = "INSERT INTO alerts (username, message) VALUES (?, ?);";
				PreparedStatement ps7 = con.prepareStatement(notifyOutbid);
				ps7.setString(1, currentUser);
				ps7.setString(2, "You have been automatically outbid on auction #" + auctionId + 
						". New bid: $" + highestAutoBid);
				ps7.executeUpdate();
			}
			
			con.commit();
			
			out.println("<p style='color:green;'>Bid placed successfully!</p>");
			out.println("<p>Your bid: $" + bidAmount + "</p>");
			if (highestAutoBidder != null) {
				out.println("<p>An automatic bid of $" + highestAutoBid + " was placed by another bidder.</p>");
			}
			out.println("<p>Redirecting to auctions page...</p>");
			response.setHeader("Refresh", "5; URL=viewAllAuctions.jsp");
		}
	} else {
		out.println("<p style='color:red;'>Error: Auction not found or not active.</p>");
		con.rollback();
	}
	
	con.setAutoCommit(true);
	db.closeConnection(con);
	
} catch (Exception e) {
	out.println("<p style='color:red;'>Error: " + e.getMessage() + "</p>");
}

      out.write("\n");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("<a href='viewAllAuctions.jsp'>[Back to All Auctions]</a>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
