/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-08 07:26:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;
import com.cs336.pkg.ApplicationDB;

public final class placeBid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/autoCloseAuctions.jsp", Long.valueOf(1765058171450L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.cs336.pkg.ApplicationDB");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Place Bid</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write('\n');

// Silently close any expired auctions
try {
	ApplicationDB db = new ApplicationDB();
	Connection con = db.getConnection();
	
	con.setAutoCommit(false);
	
	String getExpiredAuctions = "SELECT auction_id, seller, hidden_min_price, item_title FROM auction " +
			"WHERE auction_status = 'active' AND closing_date <= NOW();";
	PreparedStatement ps1 = con.prepareStatement(getExpiredAuctions);
	ResultSet rs = ps1.executeQuery();
	
	while (rs.next()) {
		int auctionId = rs.getInt("auction_id");
		String seller = rs.getString("seller");
		int hiddenMinPrice = rs.getInt("hidden_min_price");
		String itemTitle = rs.getString("item_title");
		
		String getHighestBid = "SELECT username, amount FROM bids WHERE auction_id = ? " +
				"ORDER BY amount DESC, bid_time ASC LIMIT 1;";
		PreparedStatement ps2 = con.prepareStatement(getHighestBid);
		ps2.setInt(1, auctionId);
		ResultSet bidRs = ps2.executeQuery();
		
		String winner = null;
		int winningBid = 0;
		
		if (bidRs.next()) {
			String highestBidder = bidRs.getString("username");
			int highestBid = bidRs.getInt("amount");
			
			if (highestBid >= hiddenMinPrice) {
				winner = highestBidder;
				winningBid = highestBid;
			}
		}
		
		String closeAuction = "UPDATE auction SET auction_status = 'closed' WHERE auction_id = ?;";
		PreparedStatement ps3 = con.prepareStatement(closeAuction);
		ps3.setInt(1, auctionId);
		ps3.executeUpdate();
		
		String insertAlert = "INSERT INTO alerts (username, message) VALUES (?, ?);";
		PreparedStatement ps4 = con.prepareStatement(insertAlert);
		
		if (winner != null) {
			String winnerMessage = "Congratulations! You won auction #" + auctionId + 
					" (" + itemTitle + ") with a bid of $" + winningBid;
			ps4.setString(1, winner);
			ps4.setString(2, winnerMessage);
			ps4.executeUpdate();
			
			String sellerMessage = "Your auction #" + auctionId + " (" + itemTitle + ") has closed. " +
					"Winner: " + winner + " with bid of $" + winningBid;
			ps4.setString(1, seller);
			ps4.setString(2, sellerMessage);
			ps4.executeUpdate();
		} else {
			String sellerMessage = "Your auction #" + auctionId + " (" + itemTitle + ") has closed " +
					"with no winner (reserve price not met).";
			ps4.setString(1, seller);
			ps4.setString(2, sellerMessage);
			ps4.executeUpdate();
		}
		
		String notifyLosers = "SELECT DISTINCT username FROM bids WHERE auction_id = ? AND username != ?;";
		PreparedStatement ps5 = con.prepareStatement(notifyLosers);
		ps5.setInt(1, auctionId);
		ps5.setString(2, winner != null ? winner : "");
		ResultSet losers = ps5.executeQuery();
		
		while (losers.next()) {
			String loser = losers.getString("username");
			String loserMessage = "Auction #" + auctionId + " (" + itemTitle + ") has closed. " +
					(winner != null ? "Winner: " + winner : "No winner (reserve not met)");
			ps4.setString(1, loser);
			ps4.setString(2, loserMessage);
			ps4.executeUpdate();
		}
	}
	
	con.commit();
	con.setAutoCommit(true);
	db.closeConnection(con);
	
} catch (Exception e) {
	// Silently fail - don't disrupt the page
}

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<a href='viewAllAuctions.jsp'>[Back to All Auctions]</a> <br> <br>\n");
      out.write("\n");

String auctionIdStr = request.getParameter("auction_id");
int auctionId = Integer.parseInt(auctionIdStr);
String currentUser = "" + session.getAttribute("user");

try {
	Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buyme", "root", "christian123");
    
    String sql = "SELECT a.auction_id, a.seller, a.start_price, a.bid_increment, a.closing_date, " +
    		"a.item_title, a.item_description, a.category, a.brand, a.clothing_condition, " +
    		"a.color, a.size, " +
    		"(SELECT MAX(amount) FROM bids WHERE auction_id = a.auction_id) as current_bid " +
    		"FROM auction a WHERE a.auction_id = ? AND a.auction_status = 'active';";
    
    PreparedStatement ps = con.prepareStatement(sql);
    ps.setInt(1, auctionId);
    ResultSet rs = ps.executeQuery();
    
    if (rs.next()) {
    	int startPrice = rs.getInt("start_price");
    	int bidIncrement = rs.getInt("bid_increment");
    	Integer currentBid = (Integer) rs.getObject("current_bid");
    	int minBid = (currentBid != null) ? currentBid + bidIncrement : startPrice;
    	
    	String itemTitle = rs.getString("item_title");
    	String itemDesc = rs.getString("item_description");
    	String category = rs.getString("category");
    	String brand = rs.getString("brand");
    	String condition = rs.getString("clothing_condition");
    	String color = rs.getString("color");
    	String size = rs.getString("size");
    	Timestamp closingDate = rs.getTimestamp("closing_date");

      out.write("\n");
      out.write("\n");
      out.write("<h2>Place Bid on: ");
      out.print(itemTitle);
      out.write("</h2>\n");
      out.write("\n");
      out.write("<h3>Auction Details</h3>\n");
      out.write("<table border=\"1\">\n");
      out.write("	<tr><td><strong>Item:</strong></td><td>");
      out.print(itemTitle);
      out.write("</td></tr>\n");
      out.write("	<tr><td><strong>Description:</strong></td><td>");
      out.print(itemDesc);
      out.write("</td></tr>\n");
      out.write("	<tr><td><strong>Category:</strong></td><td>");
      out.print(category);
      out.write("</td></tr>\n");
      out.write("	<tr><td><strong>Brand:</strong></td><td>");
      out.print(brand);
      out.write("</td></tr>\n");
      out.write("	<tr><td><strong>Condition:</strong></td><td>");
      out.print(condition);
      out.write("</td></tr>\n");
      out.write("	<tr><td><strong>Color:</strong></td><td>");
      out.print(color);
      out.write("</td></tr>\n");
      out.write("	<tr><td><strong>Size:</strong></td><td>");
      out.print(size);
      out.write("</td></tr>\n");
      out.write("	<tr><td><strong>Starting Price:</strong></td><td>$");
      out.print(startPrice);
      out.write("</td></tr>\n");
      out.write("	<tr><td><strong>Current Bid:</strong></td><td>$");
      out.print((currentBid != null) ? currentBid : startPrice);
      out.write("</td></tr>\n");
      out.write("	<tr><td><strong>Bid Increment:</strong></td><td>$");
      out.print(bidIncrement);
      out.write("</td></tr>\n");
      out.write("	<tr><td><strong>Closing Date:</strong></td><td>");
      out.print(closingDate);
      out.write("</td></tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("<h3>Manual Bid</h3>\n");
      out.write("<form id=\"manualBidForm\" action=\"insertBid.jsp\" method=\"POST\">\n");
      out.write("	<input type=\"hidden\" name=\"auction_id\" value=\"");
      out.print(auctionId);
      out.write("\"/>\n");
      out.write("	<input type=\"hidden\" name=\"bid_type\" value=\"manual\"/>\n");
      out.write("	Bid Amount: $<input type=\"number\" name=\"bid_amount\" min=\"");
      out.print(minBid);
      out.write("\" required/> \n");
      out.write("	(Minimum: $");
      out.print(minBid);
      out.write(")<br><br>\n");
      out.write("	<button type=\"submit\">Place Bid</button>\n");
      out.write("	<p id=\"errorMessage\" style=\"color:red;\"></p>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("<h3>Automatic Bidding</h3>\n");
      out.write("<form id=\"autoBidForm\" action=\"insertAutoBid.jsp\" method=\"POST\">\n");
      out.write("	<input type=\"hidden\" name=\"auction_id\" value=\"");
      out.print(auctionId);
      out.write("\"/>\n");
      out.write("	Upper Limit: $<input type=\"number\" name=\"upper_limit\" min=\"");
      out.print(minBid);
      out.write("\" required/><br><br>\n");
      out.write("	Bid Increment: $<input type=\"number\" name=\"bid_increment\" value=\"");
      out.print(bidIncrement);
      out.write("\" min=\"1\" required/><br><br>\n");
      out.write("	<button type=\"submit\">Set Automatic Bidding</button>\n");
      out.write("	<p id=\"autoErrorMessage\" style=\"color:red;\"></p>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("document.getElementById(\"manualBidForm\").addEventListener(\"submit\", function(event){\n");
      out.write("	const form = event.target;\n");
      out.write("	const error = document.getElementById(\"errorMessage\");\n");
      out.write("	error.textContent = \"\";\n");
      out.write("	\n");
      out.write("	const bidAmount = parseInt(form.elements[\"bid_amount\"].value);\n");
      out.write("	const minBid = ");
      out.print(minBid);
      out.write(";\n");
      out.write("	\n");
      out.write("	if (bidAmount < minBid) {\n");
      out.write("		error.textContent = \"Error: Bid must be at least $\" + minBid;\n");
      out.write("		event.preventDefault();\n");
      out.write("	}\n");
      out.write("});\n");
      out.write("\n");
      out.write("document.getElementById(\"autoBidForm\").addEventListener(\"submit\", function(event){\n");
      out.write("	const form = event.target;\n");
      out.write("	const error = document.getElementById(\"autoErrorMessage\");\n");
      out.write("	error.textContent = \"\";\n");
      out.write("	\n");
      out.write("	const upperLimit = parseInt(form.elements[\"upper_limit\"].value);\n");
      out.write("	const minBid = ");
      out.print(minBid);
      out.write(";\n");
      out.write("	\n");
      out.write("	if (upperLimit < minBid) {\n");
      out.write("		error.textContent = \"Error: Upper limit must be at least $\" + minBid;\n");
      out.write("		event.preventDefault();\n");
      out.write("	}\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");

    } else {
    	out.println("<p>Auction not found or not active.</p>");
    }
    
    con.close();
    
} catch (Exception e) {
	out.println("Error: " + e.getMessage());
}

      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
