/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-08 07:45:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.cs336.pkg.ApplicationDB;
import java.sql.*;
import com.cs336.pkg.ApplicationDB;

public final class salesReports_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/autoCloseAuctions.jsp", Long.valueOf(1765058171450L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.cs336.pkg.ApplicationDB");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Sales Reports</title>\n");
      out.write("<style>\n");
      out.write("    table { border-collapse: collapse; width: 100%; margin: 20px 0; }\n");
      out.write("    th, td { border: 1px solid black; padding: 8px; text-align: left; }\n");
      out.write("    th { background-color: #f2f2f2; }\n");
      out.write("    .section { margin: 30px 0; padding: 20px; background-color: #f9f9f9; border-radius: 5px; }\n");
      out.write("    h2 { color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }\n");
      out.write("    .total { font-weight: bold; font-size: 1.2em; color: #4CAF50; }\n");
      out.write("    .nav-links { margin: 20px 0; }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write('\n');

// Silently close any expired auctions
try {
	ApplicationDB db = new ApplicationDB();
	Connection con = db.getConnection();
	
	con.setAutoCommit(false);
	
	String getExpiredAuctions = "SELECT auction_id, seller, hidden_min_price, item_title FROM auction " +
			"WHERE auction_status = 'active' AND closing_date <= NOW();";
	PreparedStatement ps1 = con.prepareStatement(getExpiredAuctions);
	ResultSet rs = ps1.executeQuery();
	
	while (rs.next()) {
		int auctionId = rs.getInt("auction_id");
		String seller = rs.getString("seller");
		int hiddenMinPrice = rs.getInt("hidden_min_price");
		String itemTitle = rs.getString("item_title");
		
		String getHighestBid = "SELECT username, amount FROM bids WHERE auction_id = ? " +
				"ORDER BY amount DESC, bid_time ASC LIMIT 1;";
		PreparedStatement ps2 = con.prepareStatement(getHighestBid);
		ps2.setInt(1, auctionId);
		ResultSet bidRs = ps2.executeQuery();
		
		String winner = null;
		int winningBid = 0;
		
		if (bidRs.next()) {
			String highestBidder = bidRs.getString("username");
			int highestBid = bidRs.getInt("amount");
			
			if (highestBid >= hiddenMinPrice) {
				winner = highestBidder;
				winningBid = highestBid;
			}
		}
		
		String closeAuction = "UPDATE auction SET auction_status = 'closed' WHERE auction_id = ?;";
		PreparedStatement ps3 = con.prepareStatement(closeAuction);
		ps3.setInt(1, auctionId);
		ps3.executeUpdate();
		
		String insertAlert = "INSERT INTO alerts (username, message) VALUES (?, ?);";
		PreparedStatement ps4 = con.prepareStatement(insertAlert);
		
		if (winner != null) {
			String winnerMessage = "Congratulations! You won auction #" + auctionId + 
					" (" + itemTitle + ") with a bid of $" + winningBid;
			ps4.setString(1, winner);
			ps4.setString(2, winnerMessage);
			ps4.executeUpdate();
			
			String sellerMessage = "Your auction #" + auctionId + " (" + itemTitle + ") has closed. " +
					"Winner: " + winner + " with bid of $" + winningBid;
			ps4.setString(1, seller);
			ps4.setString(2, sellerMessage);
			ps4.executeUpdate();
		} else {
			String sellerMessage = "Your auction #" + auctionId + " (" + itemTitle + ") has closed " +
					"with no winner (reserve price not met).";
			ps4.setString(1, seller);
			ps4.setString(2, sellerMessage);
			ps4.executeUpdate();
		}
		
		String notifyLosers = "SELECT DISTINCT username FROM bids WHERE auction_id = ? AND username != ?;";
		PreparedStatement ps5 = con.prepareStatement(notifyLosers);
		ps5.setInt(1, auctionId);
		ps5.setString(2, winner != null ? winner : "");
		ResultSet losers = ps5.executeQuery();
		
		while (losers.next()) {
			String loser = losers.getString("username");
			String loserMessage = "Auction #" + auctionId + " (" + itemTitle + ") has closed. " +
					(winner != null ? "Winner: " + winner : "No winner (reserve not met)");
			ps4.setString(1, loser);
			ps4.setString(2, loserMessage);
			ps4.executeUpdate();
		}
	}
	
	con.commit();
	con.setAutoCommit(true);
	db.closeConnection(con);
	
} catch (Exception e) {
	// Silently fail - don't disrupt the page
}

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"nav-links\">\n");
      out.write("    <a href='adminPage.jsp'>[Back to Admin Page]</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<h1>Sales Reports</h1>\n");
      out.write("\n");

try {
    ApplicationDB db = new ApplicationDB();
    Connection con = db.getConnection();
    
    // Get all closed auctions with winners (where final bid >= reserve price)
    String getSalesData = "SELECT a.auction_id, a.seller, a.item_title, a.category, a.brand, " +
            "a.hidden_min_price, a.closing_date, " +
            "(SELECT MAX(amount) FROM bids WHERE auction_id = a.auction_id) as final_price, " +
            "(SELECT username FROM bids WHERE auction_id = a.auction_id ORDER BY amount DESC, bid_time ASC LIMIT 1) as winner " +
            "FROM auction a " +
            "WHERE a.auction_status = 'closed' " +
            "AND EXISTS (SELECT 1 FROM bids WHERE auction_id = a.auction_id) " +
            "AND (SELECT MAX(amount) FROM bids WHERE auction_id = a.auction_id) >= a.hidden_min_price " +
            "ORDER BY a.closing_date DESC;";
    
    PreparedStatement psSales = con.prepareStatement(getSalesData);
    ResultSet rsSales = psSales.executeQuery();
    
    // Store data in memory for multiple reports
    java.util.List<java.util.Map<String, Object>> sales = new java.util.ArrayList<>();
    double totalEarnings = 0;
    
    while (rsSales.next()) {
        java.util.Map<String, Object> sale = new java.util.HashMap<>();
        sale.put("auction_id", rsSales.getInt("auction_id"));
        sale.put("seller", rsSales.getString("seller"));
        sale.put("item_title", rsSales.getString("item_title"));
        sale.put("category", rsSales.getString("category"));
        sale.put("brand", rsSales.getString("brand"));
        
        // Handle final_price which might be Long from SQL MAX()
        Object priceObj = rsSales.getObject("final_price");
        Long finalPrice = null;
        if (priceObj != null) {
            finalPrice = ((Number)priceObj).longValue();
        }
        sale.put("final_price", finalPrice);
        
        sale.put("winner", rsSales.getString("winner"));
        sale.put("closing_date", rsSales.getTimestamp("closing_date"));
        sales.add(sale);
        if (finalPrice != null) {
            totalEarnings += finalPrice;
        }
    }

      out.write("\n");
      out.write("\n");
      out.write("<!-- 1. TOTAL EARNINGS -->\n");
      out.write("<div class=\"section\">\n");
      out.write("    <h2>1. Total Earnings</h2>\n");
      out.write("    <p class=\"total\">Total Earnings: $");
      out.print( String.format("%.2f", totalEarnings) );
      out.write("</p>\n");
      out.write("    <p>Total Number of Successful Sales: ");
      out.print( sales.size() );
      out.write("</p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 2. EARNINGS PER ITEM -->\n");
      out.write("<div class=\"section\">\n");
      out.write("    <h2>2. Earnings Per Item</h2>\n");
      out.write("    <table>\n");
      out.write("        <tr>\n");
      out.write("            <th>Auction ID</th>\n");
      out.write("            <th>Item Title</th>\n");
      out.write("            <th>Category</th>\n");
      out.write("            <th>Brand</th>\n");
      out.write("            <th>Seller</th>\n");
      out.write("            <th>Winner</th>\n");
      out.write("            <th>Final Price</th>\n");
      out.write("            <th>Closing Date</th>\n");
      out.write("        </tr>\n");

    for (java.util.Map<String, Object> sale : sales) {

      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td>");
      out.print( sale.get("auction_id") );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( sale.get("item_title") );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( sale.get("category") );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( sale.get("brand") );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( sale.get("seller") );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( sale.get("winner") != null ? sale.get("winner") : "N/A" );
      out.write("</td>\n");
      out.write("            <td>$");

                Object priceObj = sale.get("final_price");
                if (priceObj != null) {
                    out.print(String.format("%.2f", ((Number)priceObj).doubleValue()));
                } else {
                    out.print("0.00");
                }
            
      out.write("</td>\n");
      out.write("            <td>");
      out.print( sale.get("closing_date") );
      out.write("</td>\n");
      out.write("        </tr>\n");

    }
    
    if (sales.isEmpty()) {

      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td colspan=\"8\">No sales data available.</td>\n");
      out.write("        </tr>\n");

    }

      out.write("\n");
      out.write("    </table>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 3. EARNINGS PER ITEM TYPE -->\n");
      out.write("<div class=\"section\">\n");
      out.write("    <h2>3. Earnings Per Item Type (Category)</h2>\n");
      out.write("    <table>\n");
      out.write("        <tr>\n");
      out.write("            <th>Category</th>\n");
      out.write("            <th>Total Earnings</th>\n");
      out.write("            <th>Number of Items Sold</th>\n");
      out.write("            <th>Average Price</th>\n");
      out.write("        </tr>\n");

    // Group by category
    java.util.Map<String, java.util.List<java.util.Map<String, Object>>> byCategory = new java.util.HashMap<>();
    for (java.util.Map<String, Object> sale : sales) {
        String category = (String) sale.get("category");
        if (!byCategory.containsKey(category)) {
            byCategory.put(category, new java.util.ArrayList<>());
        }
        byCategory.get(category).add(sale);
    }
    
    for (java.util.Map.Entry<String, java.util.List<java.util.Map<String, Object>>> entry : byCategory.entrySet()) {
        String category = entry.getKey();
        java.util.List<java.util.Map<String, Object>> categorySales = entry.getValue();
        
        double categoryTotal = 0;
        for (java.util.Map<String, Object> sale : categorySales) {
            Object priceObj = sale.get("final_price");
            if (priceObj != null) {
                categoryTotal += ((Number)priceObj).doubleValue();
            }
        }
        double avgPrice = categorySales.size() > 0 ? categoryTotal / categorySales.size() : 0;

      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td>");
      out.print( category );
      out.write("</td>\n");
      out.write("            <td>$");
      out.print( String.format("%.2f", categoryTotal) );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( categorySales.size() );
      out.write("</td>\n");
      out.write("            <td>$");
      out.print( String.format("%.2f", avgPrice) );
      out.write("</td>\n");
      out.write("        </tr>\n");

    }
    
    if (byCategory.isEmpty()) {

      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td colspan=\"4\">No sales data by category available.</td>\n");
      out.write("        </tr>\n");

    }

      out.write("\n");
      out.write("    </table>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 4. EARNINGS PER END-USER (SELLER) -->\n");
      out.write("<div class=\"section\">\n");
      out.write("    <h2>4. Earnings Per End-User (Seller)</h2>\n");
      out.write("    <table>\n");
      out.write("        <tr>\n");
      out.write("            <th>Seller Username</th>\n");
      out.write("            <th>Total Earnings</th>\n");
      out.write("            <th>Number of Items Sold</th>\n");
      out.write("            <th>Average Price</th>\n");
      out.write("        </tr>\n");

    // Group by seller
    java.util.Map<String, java.util.List<java.util.Map<String, Object>>> bySeller = new java.util.HashMap<>();
    for (java.util.Map<String, Object> sale : sales) {
        String seller = (String) sale.get("seller");
        if (!bySeller.containsKey(seller)) {
            bySeller.put(seller, new java.util.ArrayList<>());
        }
        bySeller.get(seller).add(sale);
    }
    
    for (java.util.Map.Entry<String, java.util.List<java.util.Map<String, Object>>> entry : bySeller.entrySet()) {
        String seller = entry.getKey();
        java.util.List<java.util.Map<String, Object>> sellerSales = entry.getValue();
        
        double sellerTotal = 0;
        for (java.util.Map<String, Object> sale : sellerSales) {
            Object priceObj = sale.get("final_price");
            if (priceObj != null) {
                sellerTotal += ((Number)priceObj).doubleValue();
            }
        }
        double avgPrice = sellerSales.size() > 0 ? sellerTotal / sellerSales.size() : 0;

      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td>");
      out.print( seller );
      out.write("</td>\n");
      out.write("            <td>$");
      out.print( String.format("%.2f", sellerTotal) );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( sellerSales.size() );
      out.write("</td>\n");
      out.write("            <td>$");
      out.print( String.format("%.2f", avgPrice) );
      out.write("</td>\n");
      out.write("        </tr>\n");

    }
    
    if (bySeller.isEmpty()) {

      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td colspan=\"4\">No sales data by seller available.</td>\n");
      out.write("        </tr>\n");

    }

      out.write("\n");
      out.write("    </table>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 5. BEST-SELLING ITEMS -->\n");
      out.write("<div class=\"section\">\n");
      out.write("    <h2>5. Best-Selling Items</h2>\n");
      out.write("    <p>Sorted by highest final sale price</p>\n");
      out.write("    <table>\n");
      out.write("        <tr>\n");
      out.write("            <th>Rank</th>\n");
      out.write("            <th>Auction ID</th>\n");
      out.write("            <th>Item Title</th>\n");
      out.write("            <th>Category</th>\n");
      out.write("            <th>Brand</th>\n");
      out.write("            <th>Seller</th>\n");
      out.write("            <th>Final Price</th>\n");
      out.write("        </tr>\n");


    java.util.Collections.sort(sales, new java.util.Comparator<java.util.Map<String, Object>>() {
        public int compare(java.util.Map<String, Object> a, java.util.Map<String, Object> b) {
            Object priceAObj = a.get("final_price");
            Object priceBObj = b.get("final_price");
            long priceA = priceAObj != null ? ((Number)priceAObj).longValue() : 0;
            long priceB = priceBObj != null ? ((Number)priceBObj).longValue() : 0;
            return Long.compare(priceB, priceA); // Descending order
        }
    });
    
    int rank = 1;
    for (java.util.Map<String, Object> sale : sales) {
        if (rank > 10) break; // Show top 10

      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td>");
      out.print( rank++ );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( sale.get("auction_id") );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( sale.get("item_title") );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( sale.get("category") );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( sale.get("brand") );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( sale.get("seller") );
      out.write("</td>\n");
      out.write("            <td>$");

                Object priceObj2 = sale.get("final_price");
                if (priceObj2 != null) {
                    out.print(String.format("%.2f", ((Number)priceObj2).doubleValue()));
                } else {
                    out.print("0.00");
                }
            
      out.write("</td>\n");
      out.write("        </tr>\n");

    }
    
    if (sales.isEmpty()) {

      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td colspan=\"7\">No sales data available.</td>\n");
      out.write("        </tr>\n");

    }

      out.write("\n");
      out.write("    </table>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 6. BEST BUYERS -->\n");
      out.write("<div class=\"section\">\n");
      out.write("    <h2>6. Best Buyers</h2>\n");
      out.write("    <p>Users who have spent the most money (Top Buyers)</p>\n");
      out.write("    <table>\n");
      out.write("        <tr>\n");
      out.write("            <th>Rank</th>\n");
      out.write("            <th>Buyer Username</th>\n");
      out.write("            <th>Total Spent</th>\n");
      out.write("            <th>Number of Items Purchased</th>\n");
      out.write("            <th>Average Purchase Price</th>\n");
      out.write("        </tr>\n");

    // Group by buyer (winner)
    java.util.Map<String, java.util.List<java.util.Map<String, Object>>> byBuyer = new java.util.HashMap<>();
    for (java.util.Map<String, Object> sale : sales) {
        String winner = (String) sale.get("winner");
        if (winner != null) {
            if (!byBuyer.containsKey(winner)) {
                byBuyer.put(winner, new java.util.ArrayList<>());
            }
            byBuyer.get(winner).add(sale);
        }
    }
    
    // Create list of buyers with totals
    java.util.List<java.util.Map<String, Object>> buyerStats = new java.util.ArrayList<>();
    for (java.util.Map.Entry<String, java.util.List<java.util.Map<String, Object>>> entry : byBuyer.entrySet()) {
        String buyer = entry.getKey();
        java.util.List<java.util.Map<String, Object>> buyerPurchases = entry.getValue();
        
        double buyerTotal = 0;
        for (java.util.Map<String, Object> sale : buyerPurchases) {
            Object priceObj = sale.get("final_price");
            if (priceObj != null) {
                buyerTotal += ((Number)priceObj).doubleValue();
            }
        }
        
        java.util.Map<String, Object> stat = new java.util.HashMap<>();
        stat.put("buyer", buyer);
        stat.put("total", buyerTotal);
        stat.put("count", buyerPurchases.size());
        stat.put("average", buyerPurchases.size() > 0 ? buyerTotal / buyerPurchases.size() : 0);
        buyerStats.add(stat);
    }
    
    // Sort by total spent (descending)
    java.util.Collections.sort(buyerStats, new java.util.Comparator<java.util.Map<String, Object>>() {
        public int compare(java.util.Map<String, Object> a, java.util.Map<String, Object> b) {
            Double totalA = (Double) a.get("total");
            Double totalB = (Double) b.get("total");
            return totalB.compareTo(totalA); // Descending order
        }
    });
    
    rank = 1;
    for (java.util.Map<String, Object> stat : buyerStats) {
        if (rank > 10) break; // Show top 10

      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td>");
      out.print( rank++ );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( stat.get("buyer") );
      out.write("</td>\n");
      out.write("            <td>$");
      out.print( String.format("%.2f", (Double) stat.get("total")) );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( stat.get("count") );
      out.write("</td>\n");
      out.write("            <td>$");
      out.print( String.format("%.2f", (Double) stat.get("average")) );
      out.write("</td>\n");
      out.write("        </tr>\n");

    }
    
    if (buyerStats.isEmpty()) {

      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td colspan=\"5\">No buyer data available.</td>\n");
      out.write("        </tr>\n");

    }

      out.write("\n");
      out.write("    </table>\n");
      out.write("</div>\n");
      out.write("\n");

    db.closeConnection(con);
    
} catch (Exception e) {
    out.println("<div style='padding: 20px; background-color: #ffebee; border: 2px solid #f44336; border-radius: 5px; margin: 20px;'>");
    out.println("<h3 style='color: #d32f2f;'>Error generating reports</h3>");
    out.println("<p style='color: #c62828;'><strong>Error:</strong> " + e.getMessage() + "</p>");
    out.println("<details><summary>Technical Details</summary><pre>");
    e.printStackTrace(new java.io.PrintWriter(out));
    out.println("</pre></details>");
    out.println("</div>");
}

      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
