/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-06 22:33:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.sql.*;
import com.cs336.pkg.ApplicationDB;

public final class searchAuctions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/autoCloseAuctions.jsp", Long.valueOf(1765058171450L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.cs336.pkg.ApplicationDB");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Search Auctions</title>\n");
      out.write("<style>\n");
      out.write("    table { border-collapse: collapse; width: 100%; margin-top: 20px; }\n");
      out.write("    th, td { border: 1px solid black; padding: 8px; text-align: left; }\n");
      out.write("    th { background-color: #f2f2f2; }\n");
      out.write("    .closed { background-color: #ffcccc; }\n");
      out.write("    .search-form { background-color: #f9f9f9; padding: 20px; margin: 20px 0; border-radius: 5px; }\n");
      out.write("    .form-group { margin: 10px 0; }\n");
      out.write("    label { display: inline-block; width: 150px; }\n");
      out.write("    input, select { padding: 5px; width: 200px; }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write('\n');

// Silently close any expired auctions
try {
	ApplicationDB db = new ApplicationDB();
	Connection con = db.getConnection();
	
	con.setAutoCommit(false);
	
	String getExpiredAuctions = "SELECT auction_id, seller, hidden_min_price, item_title FROM auction " +
			"WHERE auction_status = 'active' AND closing_date <= NOW();";
	PreparedStatement ps1 = con.prepareStatement(getExpiredAuctions);
	ResultSet rs = ps1.executeQuery();
	
	while (rs.next()) {
		int auctionId = rs.getInt("auction_id");
		String seller = rs.getString("seller");
		int hiddenMinPrice = rs.getInt("hidden_min_price");
		String itemTitle = rs.getString("item_title");
		
		String getHighestBid = "SELECT username, amount FROM bids WHERE auction_id = ? " +
				"ORDER BY amount DESC, bid_time ASC LIMIT 1;";
		PreparedStatement ps2 = con.prepareStatement(getHighestBid);
		ps2.setInt(1, auctionId);
		ResultSet bidRs = ps2.executeQuery();
		
		String winner = null;
		int winningBid = 0;
		
		if (bidRs.next()) {
			String highestBidder = bidRs.getString("username");
			int highestBid = bidRs.getInt("amount");
			
			if (highestBid >= hiddenMinPrice) {
				winner = highestBidder;
				winningBid = highestBid;
			}
		}
		
		String closeAuction = "UPDATE auction SET auction_status = 'closed' WHERE auction_id = ?;";
		PreparedStatement ps3 = con.prepareStatement(closeAuction);
		ps3.setInt(1, auctionId);
		ps3.executeUpdate();
		
		String insertAlert = "INSERT INTO alerts (username, message) VALUES (?, ?);";
		PreparedStatement ps4 = con.prepareStatement(insertAlert);
		
		if (winner != null) {
			String winnerMessage = "Congratulations! You won auction #" + auctionId + 
					" (" + itemTitle + ") with a bid of $" + winningBid;
			ps4.setString(1, winner);
			ps4.setString(2, winnerMessage);
			ps4.executeUpdate();
			
			String sellerMessage = "Your auction #" + auctionId + " (" + itemTitle + ") has closed. " +
					"Winner: " + winner + " with bid of $" + winningBid;
			ps4.setString(1, seller);
			ps4.setString(2, sellerMessage);
			ps4.executeUpdate();
		} else {
			String sellerMessage = "Your auction #" + auctionId + " (" + itemTitle + ") has closed " +
					"with no winner (reserve price not met).";
			ps4.setString(1, seller);
			ps4.setString(2, sellerMessage);
			ps4.executeUpdate();
		}
		
		String notifyLosers = "SELECT DISTINCT username FROM bids WHERE auction_id = ? AND username != ?;";
		PreparedStatement ps5 = con.prepareStatement(notifyLosers);
		ps5.setInt(1, auctionId);
		ps5.setString(2, winner != null ? winner : "");
		ResultSet losers = ps5.executeQuery();
		
		while (losers.next()) {
			String loser = losers.getString("username");
			String loserMessage = "Auction #" + auctionId + " (" + itemTitle + ") has closed. " +
					(winner != null ? "Winner: " + winner : "No winner (reserve not met)");
			ps4.setString(1, loser);
			ps4.setString(2, loserMessage);
			ps4.executeUpdate();
		}
	}
	
	con.commit();
	con.setAutoCommit(true);
	db.closeConnection(con);
	
} catch (Exception e) {
	// Silently fail - don't disrupt the page
}

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<a href='success.jsp'>[Return to Home Page]</a>\n");
      out.write("<a href='viewAllAuctions.jsp' style='margin-left: 20px;'>[View All Auctions]</a>\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("<h2>Advanced Search</h2>\n");
      out.write("\n");
      out.write("<div class=\"search-form\">\n");
      out.write("<form method=\"GET\" action=\"searchAuctions.jsp\">\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label>Item Title:</label>\n");
      out.write("        <input type=\"text\" name=\"item_title\" placeholder=\"Search in title...\">\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label>Category:</label>\n");
      out.write("        <select name=\"category\">\n");
      out.write("            <option value=\"\">Any</option>\n");
      out.write("            <option value=\"shirt\">Shirt</option>\n");
      out.write("            <option value=\"pants\">Pants</option>\n");
      out.write("            <option value=\"hoodie\">Hoodie</option>\n");
      out.write("        </select>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label>Brand:</label>\n");
      out.write("        <input type=\"text\" name=\"brand\" placeholder=\"Enter brand...\">\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label>Size:</label>\n");
      out.write("        <select name=\"size\">\n");
      out.write("            <option value=\"\">Any</option>\n");
      out.write("            <option value=\"XS\">XS</option>\n");
      out.write("            <option value=\"S\">S</option>\n");
      out.write("            <option value=\"M\">M</option>\n");
      out.write("            <option value=\"L\">L</option>\n");
      out.write("            <option value=\"XL\">XL</option>\n");
      out.write("        </select>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label>Color:</label>\n");
      out.write("        <input type=\"text\" name=\"color\" placeholder=\"Enter color...\">\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label>Condition:</label>\n");
      out.write("        <select name=\"condition\">\n");
      out.write("            <option value=\"\">Any</option>\n");
      out.write("            <option value=\"new\">New</option>\n");
      out.write("            <option value=\"used\">Used</option>\n");
      out.write("            <option value=\"fair\">Fair</option>\n");
      out.write("        </select>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label>Min Price:</label>\n");
      out.write("        <input type=\"number\" name=\"min_price\" placeholder=\"Minimum price\">\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label>Max Price:</label>\n");
      out.write("        <input type=\"number\" name=\"max_price\" placeholder=\"Maximum price\">\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label>Status:</label>\n");
      out.write("        <select name=\"status\">\n");
      out.write("            <option value=\"\">Any</option>\n");
      out.write("            <option value=\"active\">Active Only</option>\n");
      out.write("            <option value=\"closed\">Closed Only</option>\n");
      out.write("        </select>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <label>Seller:</label>\n");
      out.write("        <input type=\"text\" name=\"seller\" placeholder=\"Search by seller username...\">\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <input type=\"submit\" value=\"Search\" style=\"width: auto; padding: 10px 20px; cursor: pointer;\">\n");
      out.write("        <input type=\"reset\" value=\"Clear\" style=\"width: auto; padding: 10px 20px; margin-left: 10px; cursor: pointer;\">\n");
      out.write("    </div>\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("\n");

String currentUser = "" + session.getAttribute("user");

// Get search parameters
String itemTitle = request.getParameter("item_title");
String category = request.getParameter("category");
String brand = request.getParameter("brand");
String size = request.getParameter("size");
String color = request.getParameter("color");
String condition = request.getParameter("condition");
String minPriceStr = request.getParameter("min_price");
String maxPriceStr = request.getParameter("max_price");
String status = request.getParameter("status");
String seller = request.getParameter("seller");

boolean hasSearchParams = (itemTitle != null && !itemTitle.isEmpty()) ||
                         (category != null && !category.isEmpty()) ||
                         (brand != null && !brand.isEmpty()) ||
                         (size != null && !size.isEmpty()) ||
                         (color != null && !color.isEmpty()) ||
                         (condition != null && !condition.isEmpty()) ||
                         (minPriceStr != null && !minPriceStr.isEmpty()) ||
                         (maxPriceStr != null && !maxPriceStr.isEmpty()) ||
                         (status != null && !status.isEmpty()) ||
                         (seller != null && !seller.isEmpty());

if (hasSearchParams) {
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buyme", "root", "christian123");
        
        // Build dynamic SQL query
        StringBuilder sql = new StringBuilder();
        sql.append("SELECT a.auction_id, a.auction_status, a.seller, a.start_price, a.bid_increment, ");
        sql.append("a.closing_date, a.item_title, a.item_description, a.category, a.brand, ");
        sql.append("a.clothing_condition, a.color, a.size, ");
        sql.append("(SELECT MAX(amount) FROM bids WHERE auction_id = a.auction_id) as current_bid, ");
        sql.append("(SELECT COUNT(*) FROM bids WHERE auction_id = a.auction_id) as bid_count ");
        sql.append("FROM auction a WHERE 1=1 ");
        
        List<Object> params = new ArrayList<Object>();
        
        if (itemTitle != null && !itemTitle.isEmpty()) {
            sql.append("AND a.item_title LIKE ? ");
            params.add("%" + itemTitle + "%");
        }
        
        if (category != null && !category.isEmpty()) {
            sql.append("AND a.category = ? ");
            params.add(category);
        }
        
        if (brand != null && !brand.isEmpty()) {
            sql.append("AND a.brand LIKE ? ");
            params.add("%" + brand + "%");
        }
        
        if (size != null && !size.isEmpty()) {
            sql.append("AND a.size = ? ");
            params.add(size);
        }
        
        if (color != null && !color.isEmpty()) {
            sql.append("AND a.color LIKE ? ");
            params.add("%" + color + "%");
        }
        
        if (condition != null && !condition.isEmpty()) {
            sql.append("AND a.clothing_condition = ? ");
            params.add(condition);
        }
        
        if (minPriceStr != null && !minPriceStr.isEmpty()) {
            try {
                int minPrice = Integer.parseInt(minPriceStr);
                sql.append("AND COALESCE((SELECT MAX(amount) FROM bids WHERE auction_id = a.auction_id), a.start_price) >= ? ");
                params.add(minPrice);
            } catch (NumberFormatException e) {
                // Ignore invalid number
            }
        }
        
        if (maxPriceStr != null && !maxPriceStr.isEmpty()) {
            try {
                int maxPrice = Integer.parseInt(maxPriceStr);
                sql.append("AND COALESCE((SELECT MAX(amount) FROM bids WHERE auction_id = a.auction_id), a.start_price) <= ? ");
                params.add(maxPrice);
            } catch (NumberFormatException e) {
                // Ignore invalid number
            }
        }
        
        if (status != null && !status.isEmpty()) {
            sql.append("AND a.auction_status = ? ");
            params.add(status);
        }
        
        if (seller != null && !seller.isEmpty()) {
            sql.append("AND a.seller LIKE ? ");
            params.add("%" + seller + "%");
        }
        
        sql.append("ORDER BY a.closing_date DESC;");
        
        PreparedStatement ps = con.prepareStatement(sql.toString());
        
        // Set parameters
        for (int i = 0; i < params.size(); i++) {
            ps.setObject(i + 1, params.get(i));
        }
        
        ResultSet rs = ps.executeQuery();
        
        boolean hasAuctions = false;

      out.write("\n");
      out.write("\n");
      out.write("<h3>Search Results</h3>\n");
      out.write("\n");
      out.write("<table>\n");
      out.write("    <tr>\n");
      out.write("        <th>Auction ID</th>\n");
      out.write("        <th>Status</th>\n");
      out.write("        <th>Item</th>\n");
      out.write("        <th>Description</th>\n");
      out.write("        <th>Category</th>\n");
      out.write("        <th>Brand</th>\n");
      out.write("        <th>Condition</th>\n");
      out.write("        <th>Color</th>\n");
      out.write("        <th>Size</th>\n");
      out.write("        <th>Start Price</th>\n");
      out.write("        <th>Current Bid</th>\n");
      out.write("        <th>Total Bids</th>\n");
      out.write("        <th>Closing Date</th>\n");
      out.write("        <th>Action</th>\n");
      out.write("    </tr>\n");
      out.write("\n");
 
        while (rs.next()) {
            hasAuctions = true;
            int auctionId = rs.getInt("auction_id");
            String auctionStatus = rs.getString("auction_status");
            String auctionSeller = rs.getString("seller");
            int startPrice = rs.getInt("start_price");
            String itemTitleResult = rs.getString("item_title");
            String itemDesc = rs.getString("item_description");
            String cat = rs.getString("category");
            String br = rs.getString("brand");
            String cond = rs.getString("clothing_condition");
            String col = rs.getString("color");
            String sz = rs.getString("size");
            Timestamp closingDate = rs.getTimestamp("closing_date");
            Integer currentBid = (Integer) rs.getObject("current_bid");
            int bidCount = rs.getInt("bid_count");
            
            int displayPrice = (currentBid != null) ? currentBid : startPrice;
            String rowClass = "closed".equals(auctionStatus) ? "class='closed'" : "";

      out.write("\n");
      out.write("\n");
      out.write("    <tr ");
      out.print(rowClass);
      out.write(">\n");
      out.write("        <td>");
      out.print(auctionId);
      out.write("</td>\n");
      out.write("        <td>");
      out.print(auctionStatus);
      out.write("</td>\n");
      out.write("        <td>");
      out.print(itemTitleResult);
      out.write("</td>\n");
      out.write("        <td>");
      out.print(itemDesc);
      out.write("</td>\n");
      out.write("        <td>");
      out.print(cat);
      out.write("</td>\n");
      out.write("        <td>");
      out.print(br);
      out.write("</td>\n");
      out.write("        <td>");
      out.print(cond);
      out.write("</td>\n");
      out.write("        <td>");
      out.print(col);
      out.write("</td>\n");
      out.write("        <td>");
      out.print(sz);
      out.write("</td>\n");
      out.write("        <td>$");
      out.print(startPrice);
      out.write("</td>\n");
      out.write("        <td>$");
      out.print(displayPrice);
      out.write("</td>\n");
      out.write("        <td>");
      out.print(bidCount);
      out.write("</td>\n");
      out.write("        <td>");
      out.print(closingDate);
      out.write("</td>\n");
      out.write("        <td>\n");
      out.write("            <a href='viewAuctionDetails.jsp?auction_id=");
      out.print(auctionId);
      out.write("'>[Details]</a>\n");
      out.write("            ");
 if ("active".equals(auctionStatus) && !auctionSeller.equals(currentUser)) { 
      out.write("\n");
      out.write("                <a href='placeBid.jsp?auction_id=");
      out.print(auctionId);
      out.write("'>[Bid]</a>\n");
      out.write("            ");
 } else if ("active".equals(auctionStatus) && auctionSeller.equals(currentUser)) { 
      out.write("\n");
      out.write("                Your auction\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                Closed\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </td>\n");
      out.write("    </tr>\n");
      out.write("\n");

        }
        
        if (!hasAuctions) {

      out.write("\n");
      out.write("    <tr>\n");
      out.write("        <td colspan=\"14\">No auctions found matching your search criteria.</td>\n");
      out.write("    </tr>\n");

        }
        
        con.close();
        
    } catch (Exception e) {
        out.println("<p style='color:red;'>Error: " + e.getMessage() + "</p>");
        e.printStackTrace();
    }
}

      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
