/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-06 22:31:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;
import com.cs336.pkg.ApplicationDB;

public final class viewAllAuctions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/autoCloseAuctions.jsp", Long.valueOf(1765058171450L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.cs336.pkg.ApplicationDB");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>All Auctions</title>\n");
      out.write("<style>\n");
      out.write("    table { border-collapse: collapse; width: 100%; }\n");
      out.write("    th, td { border: 1px solid black; padding: 8px; text-align: left; }\n");
      out.write("    th { background-color: #f2f2f2; }\n");
      out.write("    .closed { background-color: #ffcccc; }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write('\n');

// Silently close any expired auctions
try {
	ApplicationDB db = new ApplicationDB();
	Connection con = db.getConnection();
	
	con.setAutoCommit(false);
	
	String getExpiredAuctions = "SELECT auction_id, seller, hidden_min_price, item_title FROM auction " +
			"WHERE auction_status = 'active' AND closing_date <= NOW();";
	PreparedStatement ps1 = con.prepareStatement(getExpiredAuctions);
	ResultSet rs = ps1.executeQuery();
	
	while (rs.next()) {
		int auctionId = rs.getInt("auction_id");
		String seller = rs.getString("seller");
		int hiddenMinPrice = rs.getInt("hidden_min_price");
		String itemTitle = rs.getString("item_title");
		
		String getHighestBid = "SELECT username, amount FROM bids WHERE auction_id = ? " +
				"ORDER BY amount DESC, bid_time ASC LIMIT 1;";
		PreparedStatement ps2 = con.prepareStatement(getHighestBid);
		ps2.setInt(1, auctionId);
		ResultSet bidRs = ps2.executeQuery();
		
		String winner = null;
		int winningBid = 0;
		
		if (bidRs.next()) {
			String highestBidder = bidRs.getString("username");
			int highestBid = bidRs.getInt("amount");
			
			if (highestBid >= hiddenMinPrice) {
				winner = highestBidder;
				winningBid = highestBid;
			}
		}
		
		String closeAuction = "UPDATE auction SET auction_status = 'closed' WHERE auction_id = ?;";
		PreparedStatement ps3 = con.prepareStatement(closeAuction);
		ps3.setInt(1, auctionId);
		ps3.executeUpdate();
		
		String insertAlert = "INSERT INTO alerts (username, message) VALUES (?, ?);";
		PreparedStatement ps4 = con.prepareStatement(insertAlert);
		
		if (winner != null) {
			String winnerMessage = "Congratulations! You won auction #" + auctionId + 
					" (" + itemTitle + ") with a bid of $" + winningBid;
			ps4.setString(1, winner);
			ps4.setString(2, winnerMessage);
			ps4.executeUpdate();
			
			String sellerMessage = "Your auction #" + auctionId + " (" + itemTitle + ") has closed. " +
					"Winner: " + winner + " with bid of $" + winningBid;
			ps4.setString(1, seller);
			ps4.setString(2, sellerMessage);
			ps4.executeUpdate();
		} else {
			String sellerMessage = "Your auction #" + auctionId + " (" + itemTitle + ") has closed " +
					"with no winner (reserve price not met).";
			ps4.setString(1, seller);
			ps4.setString(2, sellerMessage);
			ps4.executeUpdate();
		}
		
		String notifyLosers = "SELECT DISTINCT username FROM bids WHERE auction_id = ? AND username != ?;";
		PreparedStatement ps5 = con.prepareStatement(notifyLosers);
		ps5.setInt(1, auctionId);
		ps5.setString(2, winner != null ? winner : "");
		ResultSet losers = ps5.executeQuery();
		
		while (losers.next()) {
			String loser = losers.getString("username");
			String loserMessage = "Auction #" + auctionId + " (" + itemTitle + ") has closed. " +
					(winner != null ? "Winner: " + winner : "No winner (reserve not met)");
			ps4.setString(1, loser);
			ps4.setString(2, loserMessage);
			ps4.executeUpdate();
		}
	}
	
	con.commit();
	con.setAutoCommit(true);
	db.closeConnection(con);
	
} catch (Exception e) {
	// Silently fail - don't disrupt the page
}

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<a href='success.jsp'>[Return to Home Page]</a> \n");
      out.write("<a href='searchAuctions.jsp' style='margin-left: 20px;'>[Advanced Search]</a>\n");
      out.write("<br> <br>\n");
      out.write("\n");
 
String currentUser = "" + session.getAttribute("user");

// Get sort parameter
String sortBy = request.getParameter("sort");
String sortOrder = request.getParameter("order");
if (sortBy == null || sortBy.isEmpty()) {
    sortBy = "closing_date";
}
if (sortOrder == null || sortOrder.isEmpty()) {
    sortOrder = "DESC";
}

try {
	Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buyme", "root", "christian123");
    
    // Build ORDER BY clause based on sort parameter
    String orderByClause = "ORDER BY ";
    switch(sortBy) {
        case "category":
            orderByClause += "a.category " + sortOrder;
            break;
        case "current_bid":
            orderByClause += "COALESCE((SELECT MAX(amount) FROM bids WHERE auction_id = a.auction_id), a.start_price) " + sortOrder;
            break;
        case "start_price":
            orderByClause += "a.start_price " + sortOrder;
            break;
        case "bid_count":
            orderByClause += "bid_count " + sortOrder;
            break;
        case "item_title":
            orderByClause += "a.item_title " + sortOrder;
            break;
        case "closing_date":
        default:
            orderByClause += "a.closing_date " + sortOrder;
            break;
    }
    
    String sql = "SELECT a.auction_id, a.auction_status, a.seller, a.start_price, a.bid_increment, " + 
    		"a.closing_date, a.item_title, a.item_description, a.category, a.brand, " + 
    		"a.clothing_condition, a.color, a.size, " +
    		"(SELECT MAX(amount) FROM bids WHERE auction_id = a.auction_id) as current_bid, " +
    		"(SELECT COUNT(*) FROM bids WHERE auction_id = a.auction_id) as bid_count " +
    		"FROM auction a " + orderByClause + ";";
    
    PreparedStatement ps = con.prepareStatement(sql);
    ResultSet rs = ps.executeQuery();
    
    boolean hasAuctions = false;

      out.write("\n");
      out.write("\n");
      out.write("<h2>All Auctions</h2>\n");
      out.write("\n");
      out.write("<div style=\"margin: 10px 0;\">\n");
      out.write("    <strong>Sort by:</strong>\n");
      out.write("    <a href=\"viewAllAuctions.jsp?sort=closing_date&order=DESC\">Closing Date (Newest)</a> |\n");
      out.write("    <a href=\"viewAllAuctions.jsp?sort=closing_date&order=ASC\">Closing Date (Oldest)</a> |\n");
      out.write("    <a href=\"viewAllAuctions.jsp?sort=category&order=ASC\">Category</a> |\n");
      out.write("    <a href=\"viewAllAuctions.jsp?sort=current_bid&order=DESC\">Price (High to Low)</a> |\n");
      out.write("    <a href=\"viewAllAuctions.jsp?sort=current_bid&order=ASC\">Price (Low to High)</a> |\n");
      out.write("    <a href=\"viewAllAuctions.jsp?sort=start_price&order=ASC\">Start Price</a> |\n");
      out.write("    <a href=\"viewAllAuctions.jsp?sort=bid_count&order=DESC\">Most Bids</a> |\n");
      out.write("    <a href=\"viewAllAuctions.jsp?sort=item_title&order=ASC\">Item Name</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<table>\n");
      out.write("	<tr>\n");
      out.write("		<th>Auction ID</th>\n");
      out.write("		<th>Status</th>\n");
      out.write("		<th>Item</th>\n");
      out.write("		<th>Description</th>\n");
      out.write("		<th><a href=\"viewAllAuctions.jsp?sort=category&order=ASC\">Category</a></th>\n");
      out.write("		<th>Brand</th>\n");
      out.write("		<th>Condition</th>\n");
      out.write("		<th>Color</th>\n");
      out.write("		<th>Size</th>\n");
      out.write("		<th><a href=\"viewAllAuctions.jsp?sort=start_price&order=ASC\">Start Price</a></th>\n");
      out.write("		<th><a href=\"viewAllAuctions.jsp?sort=current_bid&order=DESC\">Current Bid</a></th>\n");
      out.write("		<th>Bid Increment</th>\n");
      out.write("		<th><a href=\"viewAllAuctions.jsp?sort=bid_count&order=DESC\">Total Bids</a></th>\n");
      out.write("		<th><a href=\"viewAllAuctions.jsp?sort=closing_date&order=DESC\">Closing Date</a></th>\n");
      out.write("		<th>Action</th>\n");
      out.write("	</tr>\n");
      out.write("\n");
 
while (rs.next()) {
	hasAuctions = true;
	int auctionId = rs.getInt("auction_id");
	String status = rs.getString("auction_status");
	String seller = rs.getString("seller");
	int startPrice = rs.getInt("start_price");
	int bidIncrement = rs.getInt("bid_increment");
	String itemTitle = rs.getString("item_title");
	String itemDesc = rs.getString("item_description");
	String category = rs.getString("category");
	String brand = rs.getString("brand");
	String condition = rs.getString("clothing_condition");
	String color = rs.getString("color");
	String size = rs.getString("size");
	Timestamp closingDate = rs.getTimestamp("closing_date");
	Integer currentBid = (Integer) rs.getObject("current_bid");
	int bidCount = rs.getInt("bid_count");
	
	int displayPrice = (currentBid != null) ? currentBid : startPrice;
	String rowClass = "closed".equals(status) ? "class='closed'" : "";

      out.write("\n");
      out.write("\n");
      out.write("<tr ");
      out.print(rowClass);
      out.write(">\n");
      out.write("	<td>");
      out.print(auctionId);
      out.write("</td>\n");
      out.write("	<td>");
      out.print(status);
      out.write("</td>\n");
      out.write("	<td>");
      out.print(itemTitle);
      out.write("</td>\n");
      out.write("	<td>");
      out.print(itemDesc);
      out.write("</td>\n");
      out.write("	<td>");
      out.print(category);
      out.write("</td>\n");
      out.write("	<td>");
      out.print(brand);
      out.write("</td>\n");
      out.write("	<td>");
      out.print(condition);
      out.write("</td>\n");
      out.write("	<td>");
      out.print(color);
      out.write("</td>\n");
      out.write("	<td>");
      out.print(size);
      out.write("</td>\n");
      out.write("	<td>$");
      out.print(startPrice);
      out.write("</td>\n");
      out.write("	<td>$");
      out.print(displayPrice);
      out.write("</td>\n");
      out.write("	<td>$");
      out.print(bidIncrement);
      out.write("</td>\n");
      out.write("	<td>");
      out.print(bidCount);
      out.write("</td>\n");
      out.write("	<td>");
      out.print(closingDate);
      out.write("</td>\n");
      out.write("	<td>\n");
      out.write("		<a href='viewAuctionDetails.jsp?auction_id=");
      out.print(auctionId);
      out.write("'>[Details]</a>\n");
      out.write("		");
 if ("active".equals(status) && !seller.equals(currentUser)) { 
      out.write("\n");
      out.write("			<a href='placeBid.jsp?auction_id=");
      out.print(auctionId);
      out.write("'>[Bid]</a>\n");
      out.write("		");
 } else if ("active".equals(status) && seller.equals(currentUser)) { 
      out.write("\n");
      out.write("			Your auction\n");
      out.write("		");
 } else { 
      out.write("\n");
      out.write("			Closed\n");
      out.write("		");
 } 
      out.write("\n");
      out.write("	</td>\n");
      out.write("</tr>\n");
      out.write("\n");

}

if (!hasAuctions) {

      out.write("\n");
      out.write("<tr>\n");
      out.write("	<td colspan=\"15\">No auctions available.</td>\n");
      out.write("</tr>\n");

}

con.close();

} catch (Exception e) {
	out.println("Error: " + e.getMessage());
}

      out.write("\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
